name: json_model
description: Gernerating Dart model class from Json file.
version: 0.0.2
author: wendux <824783146@qq.com>
homepage: https://github.com/flutterchina/json_model

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.6.0
  build: ^1.5.0
  glob: ^1.2.0
  logging: ^0.11.4
  io: ^0.3.4
  build_resolvers: ^1.4.1
  build_runner_core: ^6.0.3
  build_runner: ^1.10.3
  json_annotation: ^3.1.0
  json_serializable: ^3.5.0
  path: ^1.7.0
dev_dependencies:
  test: ^1.5.1
